# Makefile.top
# Run with:  make -f Makefile.top
SIM ?= icarus
TOPLEVEL_LANG ?= verilog
SRC_DIR = $(PWD)/../src

# Whole chip + mock RAM + testbench
VERILOG_SOURCES = $(SRC_DIR)/project.v \
                  $(SRC_DIR)/bf.v \
                  $(SRC_DIR)/spi_ram.v \
                  $(SRC_DIR)/spi_master.v \
                  $(PWD)/spi_ram_model.v \
                  $(PWD)/tb_top.v

TOPLEVEL = tb_top
MODULE = test_top

include $(shell cocotb-config --makefiles)/Makefile.sim
